### PR TITLE
use specific 0.6 version number instead of release on travis

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by ma-laforge** [comment]
I was wondering if that was the thing to do.

Thanks Tony.

**Comment by tkelman** [comment]
yep, will use the latest alpha / beta / rc. no need to retag for travis-only changes, they aren't user-visible

**Comment by ma-laforge** [comment]
Perfect! Thanks.

**Comment by tkelman** [comment]
(and final and patch releases too of course once those are out)

**Pull request merged**
